flags: {}
extra-package-dbs: []
packages:
- '.'
- codec-jvm
- utils/eta-pkgdb
- utils/eta-pkg
- epm/epm
- epm/Cabal
extra-deps:
- aeson-1.0.2.1
- mmorph-1.0.9
- optparse-applicative-0.13.0.0
- turtle-1.3.0
- unix-compat-0.4.3.1
resolver: lts-6.27
