flags: {}
extra-package-dbs: []
packages:
- '.'
- codec-jvm
- utils/eta-pkgdb # TODO: Shift this to libraries/
- utils/eta-pkg
- cabalvm/epm
- cabalvm/Cabal
extra-deps:
- control-monad-exception-0.11.2
- failure-0.2.0.3
- text-1.2.2.1
resolver: lts-6.6
