allow-newer: true
extra-deps:
- binary-0.8.4.1
- cryptohash-sha256-0.11.100.1
- echo-0.1.3
- ed25519-0.0.5.0
- mintty-0.1.1
- mmorph-1.0.9
- git: https://github.com/rahulmutt/hpp.git
  commit: 75d74f53a34c875285a665d8878e5b363edfbea5
- git: https://github.com/rahulmutt/zip.git
  commit: a4fbcc9e1efc3e8623022d9fcc83b50d4cdd95a5
- tar-0.5.0.3
- text-1.2.2.1
- turtle-1.5.9
- unix-compat-0.4.3.1
- parsec-3.1.13.0
- dhall-1.19.1
- ansi-terminal-0.7.1.1
- ansi-wl-pprint-0.6.8.2
- cryptonite-0.24
- formatting-6.3.2
- megaparsec-7.0.4
- parser-combinators-1.0.0
- optparse-generic-1.3.0
- optparse-applicative-0.14.0.0
- Only-0.1
- memory-0.14.14
- basement-0.0.6
- prettyprinter-1.2.0.1
- prettyprinter-ansi-terminal-1.1.1.2
- directory-1.2.7.1
- foundation-0.0.19
- process-1.2.3.0
- repline-0.2.0.0
- haskeline-0.7.4.2
- insert-ordered-containers-0.2.1.0
- aeson-1.2.3.0
- th-abstraction-0.2.6.0
- hashable-1.2.7.0
- Diff-0.3.4
- cborg-0.2.0.0
- serialise-0.2.0.0
- dotgen-0.4.2
resolver: lts-6.27
flags:
  mintty:
    win32-2-5: false
  haskeline:
    terminfo: false
extra-package-dbs: []
packages:
- '.'
# - '../hpp' # Used for local development
# - '../zip'
- codec-jvm
- libraries/eta-boot
- libraries/eta-boot-meta
- libraries/eta-meta
- libraries/eta-repl
- utils/eta-pkg
- etlas/etlas
- etlas/etlas-cabal
- etlas/dhall-to-etlas
- etlas/hackage-security/hackage-security
- shake
